### ISSUE TITLE
iOS10 Supported only?

### ISSUE THREAD

**Issue by muukii** [totocaster/Typist#7]
I'm using with Carthage.

**Comment by totocaster** [comment]
Hey Hiroshi! I've dropped deployment target to iOS 9.0. Let me know if issue persists. Thanks!

**Comment by omaralbeik** [comment]
@totocaster Great work!, please update Typist.podspec and readme to support iOS 9 as well

**Comment by totocaster** [comment]
Done! Thanks!

**Comment by omaralbeik** [comment]
@totocaster Thank you!, It is still not updated in cocoapods, I think you should submit a new version

**Comment by totocaster** [comment]
@omaralbeik Latest version is `0.3.2` which seems to be on [CocoaPods trunk right now](https://cocoapods.org/pods/Typist). Did you try `pod outdated` and `pod update Typist`?
